### ISSUE TITLE
Printing all properties

### ISSUE THREAD

**Issue by protik77** [masumhabib/PlotPub#7]
I missed a semicolon while plotting something. Due to that it printed all the properties of plt like this:
![plotbug](https://cloud.githubusercontent.com/assets/1991215/7038439/9301bbe4-dd66-11e4-9c8b-0c67d56cbac8.PNG)

Is there any way to prevent this from your side?

This can be generated with this code:
```
clear all;
clc;

f = 50;  % frequency
Vm = 10; % peak
phi = 0; % phase
 
% generate the signal
t = [0:0.0001:3/f];
th = 2*pi*f*t;
v = Vm*sin(th+phi);

figure;
plot(t*1E3, v);

plt = Plot();

plt.XLim = [0, 80];

plt.Legend={'some'}
plt.LegendBox='on';

```

**Comment by masumhabib** [comment]
I believe, this is a feature of MATLAB. All expressions without a semicolon are printed by MATLAB. I think this is actually a very useful thing for debugging.
