### ISSUE TITLE
Save multiple files

### ISSUE THREAD

**Issue by zhidayat** [masumhabib/PlotPub#8]
Is it possible to make the function be able save multiple files with different format at a time?

**Comment by masumhabib** [comment]
I think such function will be redundant since Plot.export function can be used to do that. For example the following code will save the current figure in png, eps and jpg format:
```matlab
plt = Plot();
plt.export('file.png');
plt.export('file.eps');
plt.export('file.jpg');
```

Thanks for the suggestion.
